net.netfilter.nf_conntrack_max = 300000
net.netfilter.nf_conntrack_tcp_be_liberal = 1
# Disable IPv6 on BlueField sub-function interfaces (not used for management)
# BF-1/2/3:
net.ipv6.conf.en3f0pf0sf0.disable_ipv6 = 1
net.ipv6.conf.en3f1pf1sf0.disable_ipv6 = 1
# BF-4:
net.ipv6.conf.B21pf0sf0.disable_ipv6 = 1
net.ipv6.conf.B61c3pf0sf0.disable_ipv6 = 1
net.ipv6.conf.B61c4pf0sf0.disable_ipv6 = 1
net.netfilter.nf_flowtable_tcp_timeout = 300
