#!/bin/bash

PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"

if [ -f /etc/debian_version ]; then
	kexec --append="$(</proc/cmdline)" -l /boot/vmlinuz --ramdisk /boot/initrd.img
else
	kexec --append="$(</proc/cmdline)" -l /boot/vmlinuz-`uname -r` --ramdisk /boot/initramfs-`uname -r`.img
fi
kexec -e
